name: Apply

on:
  push:
    branches: [main]

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Apply
        env:
          GH_TOKEN: ${{ secrets.GH_INFRA_TOKEN }}
        run: gh infra apply ./repos/ --auto-approve
